[project]
name = "deep-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium-robotics[mujoco-py]>=1.4.1",
    "mujoco>=3.3.7",
    "stable-baselines3>=2.7.0",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
]
